spring.application.name=aquagrid-core

spring.datasource.url=jdbc:postgresql://localhost:5432/aquagrid
spring.datasource.username=postgres
spring.datasource.password=Arif2001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080